# Generated by Django 5.0.6 on 2024-09-12 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('numeroHistoriaClinica', models.CharField(max_length=50, unique=True)),
                ('numgestacion', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaconsulta', models.DateTimeField(auto_now_add=True)),
                ('edadgestacional', models.PositiveIntegerField(blank=True, null=True)),
                ('periodointergenesico', models.PositiveIntegerField(blank=True, null=True)),
                ('embarazonuevopareja', models.CharField(max_length=2)),
                ('hipertensioncronica', models.CharField(max_length=2)),
                ('pasistolicabasal', models.PositiveIntegerField()),
                ('padiastolicabasal', models.PositiveIntegerField()),
                ('presionsistolica1', models.PositiveIntegerField()),
                ('presiondiastolica1', models.PositiveIntegerField()),
                ('presionsistolica2', models.PositiveIntegerField()),
                ('presiondiastolica2', models.PositiveIntegerField()),
                ('testdeass', models.PositiveIntegerField()),
                ('proteinaorina', models.DecimalField(decimal_places=3, max_digits=3)),
                ('tgo', models.PositiveIntegerField()),
                ('tgp', models.PositiveIntegerField()),
                ('creatinina', models.DecimalField(decimal_places=2, max_digits=2)),
                ('urea', models.PositiveIntegerField()),
                ('fibrinogeno', models.PositiveIntegerField()),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preeclampsia.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecharegistro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('riesgo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivelriesgo', models.CharField(choices=[('LEVE', 'Leve'), ('SEVERA', 'Severa')], max_length=20)),
                ('estado', models.CharField(choices=[('Evaluado', 'Evaluado'), ('Proceso', 'Proceso')], max_length=20)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preeclampsia.historiaclinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preeclampsia.paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preeclampsia.personal')),
            ],
        ),
    ]
