# Generated by Django 5.0.6 on 2024-09-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preeclampsia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='creatinina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fibrinogeno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='proteinaorina',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tgo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tgp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='urea',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
