# Generated by Django 5.0.6 on 2024-09-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preeclampsia', '0002_alter_historiaclinica_creatinina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='proteinaorina',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
