# Generated by Django 5.1.2 on 2024-10-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preeclampsia', '0004_alter_historiaclinica_creatinina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='nivelriesgo',
            field=models.CharField(choices=[('Leve', 'Leve'), ('Severa', 'Severa')], max_length=20),
        ),
    ]
